version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
        - .:/go/src/api
    working_dir: /go/src/api
    tty: true
    ports:
      - "3000:3000"
    environment:
      DEBUG: 'true'
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: api_db